<a href="https://colab.research.google.com/github/ruwbine/dap-2024/blob/lab-3/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [4]:
# Напишите ваш код здесь
import numpy as np
matrix = np.random.random((10,10))
print(matrix)

print(matrix.min(), matrix.max())


[[0.02100559 0.58240643 0.3882746  0.97765613 0.25801307 0.69028356
  0.14158558 0.10905282 0.50821212 0.29746368]
 [0.49756004 0.36390212 0.22317415 0.57091914 0.18294798 0.23818673
  0.30719052 0.86360673 0.71786777 0.16181758]
 [0.01643404 0.15129146 0.32469015 0.79634526 0.77632388 0.59388055
  0.27677823 0.82334362 0.32223102 0.50891135]
 [0.99499614 0.87913536 0.62327665 0.86494697 0.43763109 0.56233985
  0.81623681 0.69247373 0.37360051 0.95815593]
 [0.52426585 0.06401242 0.46006224 0.68251432 0.10234973 0.09945828
  0.89583531 0.16813867 0.96080247 0.49215175]
 [0.9020941  0.97486833 0.98034125 0.67654435 0.44894069 0.14961262
  0.92311951 0.28526704 0.92733867 0.81262118]
 [0.55758153 0.55262643 0.62609273 0.33898893 0.0328646  0.43900228
  0.77916697 0.91558688 0.89290731 0.00340194]
 [0.41937171 0.2453786  0.75728548 0.0936324  0.16124355 0.8739598
  0.5325212  0.17333951 0.83549032 0.30274996]
 [0.80258987 0.1695273  0.88654407 0.03186416 0.20049637 0.48622002
  0.94157416 

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [6]:
# Напишите ваш код здесь
checked = np.zeros((8,8), dtype = int)
checked[::2, ::2] = 1
checked[1::2, 1::2] = 1

print(checked)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [8]:
z = np.arange(11)
# Напишите ваш код здесь
z[(z>3) & (z<8)] *=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [10]:
z = np.random.rand(5, 10)
# Напишите ваш код здесь
print(z)
z = z - z.mean(axis = 1, keepdims=True)
print(z)

[[0.66744854 0.40185112 0.3077972  0.30036086 0.49655775 0.67471942
  0.65383917 0.36079144 0.8824859  0.19512886]
 [0.59432696 0.93209728 0.80251179 0.08650774 0.63111432 0.61405419
  0.31775711 0.46370677 0.59290622 0.17294068]
 [0.8854748  0.39084227 0.5510156  0.19146441 0.26282941 0.549835
  0.01462564 0.60319566 0.19984938 0.40262659]
 [0.23175088 0.23386049 0.205607   0.40825687 0.77790311 0.18047314
  0.96057328 0.30122084 0.07514973 0.09335699]
 [0.37119807 0.62863625 0.81813997 0.95514422 0.66572824 0.02503086
  0.23196221 0.70463773 0.02859733 0.58908977]]
[[ 0.17335051 -0.09224691 -0.18630082 -0.19373717  0.00245972  0.1806214
   0.15974114 -0.13330658  0.38838787 -0.29896916]
 [ 0.07353465  0.41130498  0.28171949 -0.43428456  0.11032201  0.09326189
  -0.2030352  -0.05708554  0.07211391 -0.34785163]
 [ 0.48029892 -0.0143336   0.14583973 -0.21371147 -0.14234646  0.14465912
  -0.39055024  0.19801978 -0.2053265  -0.00254929]
 [-0.11506435 -0.11295474 -0.14120823  0.06144164  0

5. Поменяйте 1 и 2 строки матрицы

In [12]:
z = np.arange(25).reshape(5,5)
# Напишите ваш код здесь
print(z)
z[[0,1]] = z[[1,0]]
print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [13]:
z = np.random.random((10,2))
# Ваш код здесь
x, y = z[:,0], z[:,1]
r = np.sqrt(x**2 + y**2)
phi = np.arctan2(y, x)
polar = np.column_stack([r, phi])
print(polar)

[[0.91991564 1.08644853]
 [0.5321419  1.21865085]
 [0.7298292  0.70024902]
 [0.63083814 0.49954167]
 [0.61019525 0.12371508]
 [0.61082979 0.32774765]
 [0.293781   0.67711879]
 [0.51648331 1.0427026 ]
 [0.26559939 1.43558569]
 [0.53202028 0.46303256]]


7. Заменить максимальный элемент массива на ноль

In [31]:
z = np.random.random(10)
# Ваш код здесь

z[z.argmax()] = 0

8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [30]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
# Напишите ваш код здесь
z[np.unique(i)] += 1

9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [29]:
z = np.array([1,2,3,4,5])
# Напишите ваш код здесь
vec = np.zeros(len(z) * 4 - 3, dtype = int)
vec[::4] = z

10. Найти ближайшее к заданному значению число в заданном массиве

In [27]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
# Напишите ваш код здесь
z[np.abs(z - v).argmin()]

np.int64(27)

## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3]) #int64
np.array([1., 4, 2, 5, 3]) #float64
np.array([1, 4, 2, 5, 3], dtype='float128') #float128
np.array([1., 4, 2, 5, 3], dtype='complex128') #complex128
np.array([1, 4, 2, 5, 3], dtype ='float64') #float64
np.array([1, 4, 2, 5, 3], dtype =int64) #int64
np.array([1, 4, 2, 5, 3], dtype='bool') #bool
np.array([1, 4, 2, 5, 3], dtype='str') #str
np.array([1, 4, 2, 5, '3']) #str
np.array([1, -4, 2, 0, 1j]) #complex128
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

1) `'4'+'1' = '41`
2) `True`
3) `False`
4) `1`
5) `int() argument must be a string, a bytes-like object or a real number, not 'complex'`
6) `'333'`

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float) # матрица 3х5 из 1
np.full((3, 5), 3.14) # матрица, где каждое значение - число Пи
np.linspace(0, 1, 5) # [0, 0.25, 0.5, 0.75, 1]
np.diag((1,3,5)) # диагональная матрица
np.smile((1,3,5)) # ошибка(такой функции нет)
np.random.random((3, 3)) # случайные значения в матрице 3х3
np.eye(3) # единичная матрица
np.empty(3) # мусор в памяти
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]           # 3
X[-1,-1]         # 7
X[0:1,-1]        # [4]
X[0:2,-1]        # [4, 8]
X[0:2,0:2]       # [[3,5],[7,6]]
X[1,1:3]         # [6,8]
X[1,:]           # [7,6,8,8]
X[:,:]           # весь массив
X[:]             # весь массив
X[::2,::2]       # [[3,2],[1,7]]
X[0:3:2,0:3:2]   # то же самое
X[::-1,::-1]     # перевёрнутый массив

```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2]) # разрез по строкам, первые 2 строки и потом остальное
np.split(grid, [2], axis=1) # разрез по столбцам, первые 2 столбца и т.д.
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1] # конкатенация массива, т.е на выходе будет [1,2,3,3,2,1]
    np.array([1, 2, 3]) + np.array([3, 2, 1]) # элементарное сложение, т.е каждый элемент будет складывается по похожему индексу в массивах. i[0] + j[0], i[1] + j[1] и т.д.
```

**7**. Как в CodeLab измерить время выполнения кода?

С помощью:
```
%time
%timeit

```

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)          # сумма всех элементов
np.sum(M, axis=1)  # сумма по строкам
np.sum(M, axis=0)  # сумма по столбцам
np.sum(M, axis=2)  # ОШИБКА (нет 3-й оси)
np.sum(M, 1)       # то же, что axis=1
sum(M)             # сумма строк (пайтоновская)
sum(M,1)           # ОШИБКА

```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3       # [False, False, False, True]
X < 3       # [True, True, False, False]
X[X < 3]    # [1,2]
X[X > 3]    # [4]
X[X != 3]   # [1,2,4]

```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Основное преимущество: скорость за счёт векторизации и работы в C

NumPy хранит данные в непрерывном блоке памяти и использует оптимизированный код на C/Fortran, что делает операции в десятки раз быстрее, чем Python-списки.